### PR TITLE
chore: updated to 8.0

### PR DESCRIPTION
**Pull request by alexmgriffiths**
feat: Support for PHP 8
Probably? My machine wouldn't let me test. I hate WSL2.
Verified the docker image for php:8-cli exists and changed 7.4 to 8.

### CODE REVIEW

**Comment by alexmgriffiths** [comment]
@StephaneBour Honestly have no idea how to satisfy the pr-lint at this point.

**Comment by StephaneBour** [comment]
> @StephaneBour Honestly have no idea how to satisfy the pr-lint at this point.

Hello, just use the angular convention (chore: update for PHP 8) in PR title.

**Comment by alexmgriffiths** [comment]
@StephaneBour Ah, thank you. Should I submit a new PR? Sorry, have never worked with git on anything open-source, just use it for internal work repos and we happen to use this

**Comment by alexmgriffiths** [comment]
@StephaneBour Nevermind, submitted new PR with fixed title and it passed. Thank you

**Pull request closed without merging**
